---
engines:
  tailor:
    enabled: true
    checks:
      comment-whitespace:
        enabled: false
      colon-whitespace:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "**.swift"
exclude_paths: []
